namespace AOSharp.Common.GameData
{
    public enum IdentityType
    {
        None = 0x00,
        WeaponPage = 0x65,
        ArmorPage = 0x66,
        ImplantPage = 0x67,
        Inventory = 0x68,
        Bank = 0x69,
        Reclaim = 0x6A,
        Backpack = 0x6B,
        KnuBotTradeWindow = 0x6C,
        OverflowWindow = 0x6E,
        TradeWindow = 0x6F,
        SocialPage = 0x73,
        ShopInventory = 0x767,
        PlayerShopInventory = 0x790,
        PlayfieldUnk = 0x9C43,
        Playfield2 = 0x9C50,
        SimpleChar = 0xC350,
        CityController = 0xC418,
        Terminal = 0xC73D,
        Door = 0xC748,
        Container = 0xC749,
        WeaponInstance = 0xC74A,
        VendingMachine = 0xC75B,
        TempBag = 0xC767,
        Corpse = 0xC76A,
        MissionKey = 0xC76D,
        MissionKeyDuplicator = 0xC76E,
        MailTerminal = 0xC773,
        Playfield1 = 0xC79C,
        Playfield = 0xC79D,
        NanoProgram = 0xCF1B,
        GfxEffect = 0xCF26,
        ACGEntrance = 0xDAC6,
        MissionTerminal = 0xDCA1,
        TeamWindow = 0xDEA9,
        Organization = 0xDEAA,
        IncomingTradeWindow = 0xDEAD,
        Playfield3 = 0x186A1,
    }
}
